name: extract_data

on:
  schedule:
    - cron: '0 * * * *' # Execute very hour 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Add Repo
        uses: actions/checkout@v4 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      
      - name: Install necesarry packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/data_extraction/requirements.txt
          
      - name: Execute Data Extraction 
        run: python src/data_extraction/extract_data.py
      
      - name: Update new data to Github
        run: bash src/data_extraction/push_to_main.sh

